language: node_js
node_js:
  - "node"
cache:
  yarn: true
  directories:
    - node_modules
script:
  - yarn test && yarn build
deploy:
  - provider: s3
    access_key_id: $EWEEK_ACCESS_KEY
    secret_access_key: $EWEEK_SECRET_KEY
    bucket: "www.eweekillinois.org"
    skip_cleanup: true
    region: us-east-1
    local-dir: build
    on:
      branch: master
      
